[project]
name = "doordash-businessanalysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
]
